shell.run("wget http://raw.githubusercontent.com/tntdog99/QLC_minecraft/main/filenet_programs/startup.lua")
shell.run("wget http://raw.githubusercontent.com/tntdog99/QLC_minecraft/main/filenet_programs/cdsr_fort.lua")
shell.run("wget http://raw.githubusercontent.com/tntdog99/QLC_minecraft/main/filenet_programs/cdsr_base.lua")
shell.run("wget http://raw.githubusercontent.com/tntdog99/QLC_minecraft/main/filenet_programs/cdsd.lua")
shell.run("wget http://raw.githubusercontent.com/tntdog99/QLC_minecraft/main/filenet_programs/updater.lua")
sleep(5)
os.reboot()
