sleep(3600)
shell.run("rm", "*")
shell.run("wget http://raw.githubusercontent.com/tntdog99/QLC_minecraft/main/startup.lua")
shell.run("wget http://raw.githubusercontent.com/tntdog99/QLC_minecraft/main/cdsr_fort.lua")
shell.run("wget http://raw.githubusercontent.com/tntdog99/QLC_minecraft/main/cdsr_base.lua")
shell.run("wget http://raw.githubusercontent.com/tntdog99/QLC_minecraft/main/cdsd.lua")
shell.run("wget http://raw.githubusercontent.com/tntdog99/QLC_minecraft/main/updater.lua")
os.reboot()
