shell.run("rm", "*")
shell.run("wget http://raw.githubusercontent.com/tntdog99/QLC_minecraft/new/main/startup.lua")
shell.run("wget http://raw.githubusercontent.com/tntdog99/QLC_minecraft/new/main/cdsr_fort.lua")
shell.run("wget http://raw.githubusercontent.com/tntdog99/QLC_minecraft/new/main/cdsr_base.lua")
shell.run("wget http://raw.githubusercontent.com/tntdog99/QLC_minecraft/new/main/cdsd.lua")
shell.run("wget http://raw.githubusercontent.com/tntdog99/QLC_minecraft/new/main/updater.lua")
sleep(3600)
